version: "3.7"

services:
    caddy:
        image: caddy:latest
        container_name: caddy
        restart: unless-stopped
        security_opt:
            - no-new-privileges:true
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - "/etc/timezone:/etc/timezone:ro"
            - "/etc/localtime:/etc/localtime:ro"
            - "./etc/caddy/data:/data"
            - "./etc/caddy/config:/config"
            - "./etc/caddy/sites:/etc/caddy/sites"
            - "./etc/caddy/Caddyfile:/etc/caddy/Caddyfile"
        networks:
            caddy-net:
                ipv4_address: 172.28.240.2
        depends_on:
            - pihole
            - monitorix

    pihole:
        image: pihole/pihole:latest
        container_name: pihole
        restart: unless-stopped
        ports:
            - "53:53/tcp"
            - "53:53/udp"
            - "67:67/udp"
        expose:
            - "80"
        environment:
            TZ: "Asia/Hong_Kong"
            WEBPASSWORD: "${WEB_PASSWORD}"
            DNS1: "172.28.241.6#5053"
            DNS2: "172.28.241.6#5053"
        volumes:
            - "/etc/timezone:/etc/timezone:ro"
            - "/etc/localtime:/etc/localtime:ro"
            - "./etc/pihole:/etc/pihole"
            - "./etc/dnsmasq.d:/etc/dnsmasq.d"
        dns:
            - 1.1.1.1
        networks:
            caddy-net:
                ipv4_address: 172.28.240.4
            pihole-net:
                ipv4_address: 172.28.241.4
        depends_on:
            - dnscrypt_proxy

    dnscrypt_proxy:
        image: klutchell/dnscrypt-proxy:latest
        container_name: dnscrypt_proxy
        restart: unless-stopped
        expose:
            - "5053/udp"
            - "5053/tcp"
        volumes:
            - "/etc/timezone:/etc/timezone:ro"
            - "/etc/localtime:/etc/localtime:ro"
            - "./etc/dnscrypt-proxy/config:/config"
        networks:
            pihole-net:
                ipv4_address: 172.28.241.6

    coredns:
        image: coredns/coredns:latest
        container_name: coredns
        restart: unless-stopped
        command: "-conf /etc/coredns/Corefile"
        ports:
            - "853:853/tcp"
            - "853:853/udp"
        volumes:
            - "/etc/timezone:/etc/timezone:ro"
            - "/etc/localtime:/etc/localtime:ro"
            - "./etc/coredns:/etc/coredns"
        networks:
            pihole-net:
                ipv4_address: 172.28.241.2
        depends_on:
            - pihole

    monitorix:
        image: beartums/rpi-monitorix:latest
        container_name: monitorix
        restart: unless-stopped
        devices:
            - "/dev/vchiq:/dev/vchiq"
        environment:
            MONITORIX_HOSTNAME: "pi-hole"
            TITLE: "Pi-Hole Status"
            REFRESH_RATE: 150
            TEMPERATURE_SCALE: "c"
            HTTPD-GROUP: "www-data"
            GRAPHS: "system,raspberrypi,kern,proc,process,int,serv,net"
        expose:
            - "8080"
        volumes:
            - "/etc/timezone:/etc/timezone:ro"
            - "/etc/localtime:/etc/localtime:ro"
            - "./etc/monitorix/conf.d:/etc/monitorix/conf.d"
            - "./etc/monitorix/lib:/etc/monitorix/lib"
            - "./etc/monitorix/www:/etc/monitorix/www"
            - "./etc/monitorix/assets:/assets"
        networks:
            caddy-net:
                ipv4_address: 172.28.240.8
            pihole-net:
                ipv4_address: 172.28.241.8

networks:
    caddy-net:
        name: caddy-net
        external: true
        ipam:
            config:
                - subnet: 172.28.240.0/24

    pihole-net:
        name: pihole-net
        ipam:
            config:
                - subnet: 172.28.241.0/24
