version: "3.7"

services:
    vaultwarden:
        image: vaultwarden/server:latest
        container_name: vaultwarden
        restart: always
        environment:
            - TZ=${TZ}
            - DOMAIN=${VAULTWARDEN_DOMAIN}
            - DATA_FOLDER=${VAULTWARDEN_DATA_FOLDER}
            - DATABASE_URL=${VAULTWARDEN_DATABASE_URL}
            - ATTACHMENTS_FOLDER=${VAULTWARDEN_ATTACHMENTS_FOLDER}
            - ICON_CACHE_FOLDER=${VAULTWARDEN_ICON_CACHE_FOLDER}
            - DISABLE_ADMIN_TOKEN=${VAULTWARDEN_DISABLE_ADMIN_TOKEN}
            - ADMIN_TOKEN=${VAULTWARDEN_ADMIN_TOKEN}
            - SIGNUPS_ALLOWED=${VAULTWARDEN_SIGNUPS_ALLOWED}
            - INVITATIONS_ALLOWED=${VAULTWARDEN_INVITATIONS_ALLOWED}
            - WEBSOCKET_ENABLED=${VAULTWARDEN_WEBSOCKET_ENABLED}
            - DISABLE_2FA_REMEMBER=${VAULTWARDEN_DISABLE_2FA_REMEMBER}
            - SMTP_HOST=${VAULTWARDEN_SMTP_HOST}
            - SMTP_FROM=${VAULTWARDEN_SMTP_FROM}
            - SMTP_FROM_NAME=${VAULTWARDEN_SMTP_FROM_NAME}
            - SMTP_SECURITY=${VAULTWARDEN_SMTP_SECURITY}
            - SMTP_PORT=${VAULTWARDEN_SMTP_PORT}
            - SMTP_USERNAME=${VAULTWARDEN_SMTP_USERNAME}
            - SMTP_PASSWORD=${VAULTWARDEN_SMTP_PASSWORD}
            - SMTP_TIMEOUT=${VAULTWARDEN_SMTP_TIMEOUT}
        volumes:
            - "./etc/vaultwarden/data:/data"
        networks:
            caddy-net:
                ipv4_address: 172.28.240.8

networks:
    caddy-net:
        name: caddy-net
        external: true
