version: "3.7"

services:
    caddy:
        container_name: caddy
        build: ./docker/caddy
        restart: unless-stopped
        security_opt:
            - no-new-privileges:true
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - "./etc/caddy/data:/data"
            - "./etc/caddy/config:/config"
            - "./etc/caddy/sites:/etc/caddy/sites"
            - "./etc/caddy/Caddyfile:/etc/caddy/Caddyfile"
        networks:
            caddy-net:
                ipv4_address: 172.28.240.2
        depends_on:
            - adguard_home

    adguard_home:
        image: adguard/adguardhome:latest
        container_name: adguard_home
        restart: always
        ports:
            - "53:53"
            - "853:853/tcp"
        expose:
            - "80/tcp"
            - "3000/tcp"
        environment:
            - TZ=${TZ}
        volumes:
            - "./etc/adguard-home/work:/opt/adguardhome/work"
            - "./etc/adguard-home/conf:/opt/adguardhome/conf"
            - "./etc/caddy/data/certificates:/opt/caddy/data/certificates:ro"
        networks:
            caddy-net:
                ipv4_address: 172.28.240.4
            adguard-home-net:
                ipv4_address: 172.28.241.2

    cloudflare_ddns:
        image: oznu/cloudflare-ddns:latest
        container_name: cloudlfare_ddns
        restart: always
        environment:
            API_KEY: "${CLOUDFLARE_DDNS_API_KEY}"
            ZONE: "${CLOUDFLARE_DDNS_ZONE}"
            SUBDOMAIN: "${CLOUDFLARE_DDNS_DOMAIN}"
            PROXIED: "false"
        networks:
            caddy-net:
                ipv4_address: 172.28.240.6
            adguard-home-net:
                ipv4_address: 172.28.241.4

networks:
    caddy-net:
        name: caddy-net
        external: true

    adguard-home-net:
        name: adguard-home-net
        ipam:
            config:
                - subnet: 172.28.241.0/24
