version: "3.7"

services:
    caddy:
        container_name: caddy
        build: ./docker/caddy
        restart: unless-stopped
        security_opt:
            - no-new-privileges:true
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - "/etc/timezone:/etc/timezone:ro"
            - "/etc/localtime:/etc/localtime:ro"
            - "./etc/caddy/data:/data"
            - "./etc/caddy/config:/config"
            - "./etc/caddy/sites:/etc/caddy/sites"
            - "./etc/caddy/Caddyfile:/etc/caddy/Caddyfile"
        networks:
            caddy-net:
                ipv4_address: 172.28.240.2
        depends_on:
            - pihole
            - monitorix

    pihole:
        image: pihole/pihole:latest
        container_name: pihole
        hostname: pihole
        restart: unless-stopped
        ports:
            - "53:53/tcp"
            - "53:53/udp"
            # Disable the DHCP service port binding
            #- "67:67/udp"
        expose:
            - "80"
        environment:
            TZ: "Asia/Hong_Kong"
            WEBPASSWORD: "${WEB_PASSWORD}"
            DNS1: "172.28.241.6#5053"
            DNS2: "172.28.241.6#5053"
            # Listen on all interface not only eth1 by default
            # and change the default listen eth0 to eth1 for fallback to pihole-net
            # normal:
            # - clinet <-> pihole <-> dnscrypt_proxy
            # - clinet <-> coredns <-> pihole <-> dnscrypt_proxy
            # fallback:
            # - clinet <-> coredns <-> pihole <-> dnscrypt_proxy
            INTERFACE: "eth1"
            DNSMASQ_LISTENING: "all"
            DNSMASQ_USER: "pihole"
        volumes:
            - "/etc/timezone:/etc/timezone:ro"
            - "/etc/localtime:/etc/localtime:ro"
            - "./etc/pihole:/etc/pihole"
            - "./etc/dnsmasq.d:/etc/dnsmasq.d"
        dns:
            - 1.1.1.1
        networks:
            caddy-net:
                ipv4_address: 172.28.240.4
            pihole-net:
                ipv4_address: 172.28.241.4
        depends_on:
            - dnscrypt_proxy

    dnscrypt_proxy:
        image: klutchell/dnscrypt-proxy:latest
        container_name: dnscrypt_proxy
        restart: unless-stopped
        expose:
            - "5053/udp"
            - "5053/tcp"
        volumes:
            - "/etc/timezone:/etc/timezone:ro"
            - "/etc/localtime:/etc/localtime:ro"
            - "./etc/dnscrypt-proxy/config:/config"
        networks:
            pihole-net:
                ipv4_address: 172.28.241.6

    coredns:
        container_name: coredns
        build: ./docker/coredns
        restart: unless-stopped
        command: "-conf /etc/coredns/Corefile"
        ports:
            - "853:853/tcp"
            - "853:853/udp"
        expose:
            - "9253"
        volumes:
            - "/etc/timezone:/etc/timezone:ro"
            - "/etc/localtime:/etc/localtime:ro"
            - "./etc/coredns:/etc/coredns"
            - "./etc/caddy/data:/data:ro"
        networks:
            pihole-net:
                ipv4_address: 172.28.241.2
        depends_on:
            - caddy
            - pihole
            - dnscrypt_proxy

    monitorix:
        image: beartums/rpi-monitorix:latest
        container_name: monitorix
        restart: unless-stopped
        devices:
            - "/dev/vchiq:/dev/vchiq"
        environment:
            MONITORIX_HOSTNAME: "pi-hole"
            TITLE: "Pi-Hole Status"
            REFRESH_RATE: 150
            TEMPERATURE_SCALE: "c"
            HTTPD-GROUP: "www-data"
            GRAPHS: "system,raspberrypi,kern,proc,process,int,serv,net"
        expose:
            - "8080"
        volumes:
            - "/etc/timezone:/etc/timezone:ro"
            - "/etc/localtime:/etc/localtime:ro"
            - "./etc/monitorix/conf.d:/etc/monitorix/conf.d"
            - "./etc/monitorix/assets:/assets"
            - "./etc/monitorix/data:/var/lib/monitorix/data"
        networks:
            caddy-net:
                ipv4_address: 172.28.240.8
            pihole-net:
                ipv4_address: 172.28.241.8
        # Enable iptables command
        cap_add:
            - NET_ADMIN

    prometheus:
        image: prom/prometheus:latest
        container_name: prometheus
        restart: unless-stopped
        command:
            - "--config.file=/etc/prometheus/conf/prometheus.yml"
            - "--storage.tsdb.path=/etc/prometheus/data"
            - "--storage.tsdb.retention.time=15d"
            - "--web.console.libraries=/etc/prometheus/console_libraries"
            - "--web.console.templates=/etc/prometheus/consoles"
            - "--web.enable-lifecycle"
        expose:
            - "9090"
        volumes:
            - "/etc/timezone:/etc/timezone:ro"
            - "/etc/localtime:/etc/localtime:ro"
            - "./etc/prometheus/conf/prometheus.yml:/etc/prometheus/conf/prometheus.yml:ro"
            - "./etc/prometheus/data:/etc/prometheus/data"
        networks:
            caddy-net:
                ipv4_address: 172.28.240.10
            pihole-net:
                ipv4_address: 172.28.241.10
            monitor-net:
                ipv4_address: 172.28.242.2
        depends_on:
            - cadvisor
            - node_exporter

    cadvisor:
        image: zcube/cadvisor:latest
        container_name: cadvisor
        restart: unless-stopped
        privileged: true
        devices:
            - "/dev/kmsg:/dev/kmsg"
        expose:
            - "8080"
        volumes:
            - "/etc/timezone:/etc/timezone:ro"
            - "/etc/localtime:/etc/localtime:ro"
            - "/:/rootfs:ro"
            - "/var/run:/var/run:ro"
            - "/sys:/sys:ro"
            - "/var/lib/docker/:/var/lib/docker:ro"
            - "/dev/disk/:/dev/disk:ro"
        networks:
            monitor-net:
                ipv4_address: 172.28.242.4

    node_exporter:
        image: prom/node-exporter:v1.0.1
        container_name: node_exporter
        restart: unless-stopped
        command:
            - '--path.procfs=/host/proc'
            - '--path.sysfs=/host/sys'
            - '--path.rootfs=/rootfs'
            - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
        expose:
            - "9100"
        volumes:
            - "/etc/timezone:/etc/timezone:ro"
            - "/etc/localtime:/etc/localtime:ro"
            - "/proc:/host/proc:ro"
            - "/sys:/host/sys:ro"
            - "/:/rootfs:ro"
        networks:
            monitor-net:
                ipv4_address: 172.28.242.6

    pihole_exporter:
        image: ekofr/pihole-exporter:latest
        container_name: pihole_exporter
        restart: unless-stopped
        environment:
            PIHOLE_HOSTNAME: "pihole"
            PIHOLE_PASSWORD: "${WEB_PASSWORD}"
            INTERVAL: "30s"
            PORT: "9617"
        expose:
            - "9617"
        networks:
            pihole-net:
                ipv4_address: 172.28.241.12
            monitor-net:
                ipv4_address: 172.28.242.8

networks:
    caddy-net:
        name: caddy-net
        external: true
        ipam:
            config:
                - subnet: 172.28.240.0/24

    pihole-net:
        name: pihole-net
        ipam:
            config:
                - subnet: 172.28.241.0/24

    monitor-net:
        name: monitor-net
        ipam:
            config:
                - subnet: 172.28.242.0/24
