{
 "title": "PI-Hole Exporter",
 "description": "This is a PI-Hole dashboard when using the https://github.com/eko/pihole-exporter Prometheus exporter",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "🍓PI-Hole", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "pihole_status", "legendFormat": "{{ legend }}" }
   ]
  },
  {
   "title": "Queries Today",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "pihole_dns_queries_today" }
   ]
  },
  {
   "title": "Blocked Today",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "pihole_ads_blocked_today" }
   ]
  },
  {
   "title": "Total blocked",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "pihole_domains_being_blocked" }
   ]
  },
  {
   "title": "Unique domains",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 11, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "pihole_unique_domains" }
   ]
  },
  {
   "title": "Top queries by domain",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 3, "x": 15, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "pihole_top_queries", "legendFormat": "{{ domain }}" }
   ]
  },
  {
   "title": "Replies by type",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 3, "x": 18, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "pihole_reply", "legendFormat": "{{ type }}" }
   ]
  },
  {
   "title": "Top ads by domain",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "pihole_top_ads", "legendFormat": "{{ domain }}" }
   ]
  },
  {
   "title": "% ads blocked",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 11, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "pihole_ads_percentage_today" }
   ]
  },
  {
   "title": "CPU used%",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(1 - avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) by (instance)) * 100",
     "legendFormat": "CPU used"
    }
   ]
  },
  {
   "title": "Memory used%",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes / (node_memory_MemTotal_bytes)))* 100",
     "legendFormat": "memory used"
    }
   ]
  },
  {
   "title": "Partition used%",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max((node_filesystem_size_bytes{fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{fstype=~\"ext.?|xfs\"}) *100/(node_filesystem_avail_bytes {fstype=~\"ext.?|xfs\"}+(node_filesystem_size_bytes{fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{fstype=~\"ext.?|xfs\"})))by(instance)",
     "legendFormat": "Partition used"
    }
   ]
  },
  {
   "title": "CPU temp%",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 5, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "rpi_cpu_temperature_celsius", "legendFormat": "CPU temp" }
   ]
  },
  {
   "title": "GPU temp%",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 5, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "rpi_cpu_temperature_celsius", "legendFormat": "GPU temp" }
   ]
  },
  {
   "title": "DNS queries all of types",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "pihole_dns_queries_all_types", "legendFormat": "{{ job }}" }
   ]
  },
  {
   "title": "Queries cached/forwarded",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "pihole_queries_cached", "legendFormat": "Queries cached" },
    { "expr": "pihole_queries_forwarded", "legendFormat": "Queries forwarded" }
   ]
  },
  {
   "title": "DNS Query types",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "pihole_querytypes", "legendFormat": "{{ type }}" },
    {}
   ]
  },
  {
   "title": "Ads blocked (today)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "pihole_ads_blocked_today", "legendFormat": "{{ job }}" }
   ]
  },
  {
   "title": "% of ads blocked",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "pihole_ads_percentage_today", "legendFormat": "{{ job }}" }
   ]
  },
  {
   "title": "Unique clients",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "pihole_unique_clients" }
   ]
  },
  {
   "title": "Top queries",
   "type": "table-old",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 19 },
   "targets": [
    { "expr": "pihole_top_queries", "legendFormat": "{{ domain }}" }
   ]
  },
  {
   "title": "Top ads domains",
   "type": "table-old",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 19 },
   "targets": [
    { "expr": "pihole_top_ads", "legendFormat": "{{ domain }}" }
   ]
  },
  {
   "title": "Forward destinations",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "pihole_forward_destinations", "legendFormat": "{{ destination }}" }
   ]
  }
 ]
}